### PR TITLE
Add theme documentation

### PR DESCRIPTION
**Pull request by Lootyhoof**
This adds the theme documentation as-is converted from the old wiki, with a few touchups.

### CODE REVIEW

**Comment by mattatobin** [comment]
I dunno what you changed in site.php but you didn't update the content array constant.

**Comment by Lootyhoof** [comment]
>but you didn't update the content array constant.

I did though? I removed `true` from the pages I added which removes the flag you had set to indicate those pages weren't ready yet. Or was there somewhere else?

**Comment by Lootyhoof** [comment]
Though I do now see a small typo in one of the page titles which I'll send a fix for.

**Comment by mattatobin** [comment]
You're right sorry.. Mobile managed the files changed.

**Pull request merged**
